training_data_slack = [("I absolutely love the outcome", 'positive'),
                       ("This view is amazing", 'positive'),
                       ("I feel great about this", 'positive'),
                       ("I am so excited about the demo", 'positive'),
                       ("The changes look good", 'positive'),
                       ("All tasks are done", 'positive'),
                       ("This is awesome guys", 'positive'),
                       ("All changes are verified in QA", 'positive'),
                       ("All changes are verified in Production", 'positive'),
                       ("The build is bug free", 'positive'),
                       ("The client was happy with our demo", 'positive'),
                       ("I feel particularly happy today seeing that this works fine", 'positive'),
                       ("I didn't expect this to be completed in time much less before it. Awesome work", 'positive'),
                       ("Okay. I'll have to ask someone for help on this task", 'neutral'),
                       ("Is this really required? This statement here?", 'neutral'),
                       ("Front end changes already done", 'neutral'),
                       ("I will let you know the status by the evening", 'neutral'),
                       ("Can you update the timesheet", 'neutral'),
                       ("Can you update Jira", 'neutral'),
                       ("will this be done in time", 'neutral'),
                       ("I shall see and come back", 'neutral'),
                       ("how do I do this. Any thoughts?", 'neutral'),
                       ("Let's have a scrum and then decide on these tickets", 'neutral'),
                       ("Are you guys stuck anywhere or need anyone's help?", 'neutral'),
                       ("Lets go for team dinner today", 'neutral'),
                       ("I am looking into the issue. Will give updates soon", 'neutral'),
                       ("are the wireframes ready", 'neutral'),
                       ("We are already closing the connection", 'neutral'),
                       ("Updated RDS Password. And revoked all access except S3 Access for the developers.", 'neutral'),
                       ("Code Commits for Moving meetm.in to app.meetm.in", 'neutral'),
                       ("Not reproducible. This ticket can be closed.", 'neutral'),
                       ("Okay I'll let you know in sometime", 'neutral'),
                       ("Added review comments to the request", 'neutral'),
                       ("Raised a PR. Kindly review", 'neutral'),
                       ("Just get in touch with someone who can help you on this", 'neutral'),
                       ("This is not what we expected", 'negative'),
                       ("The Production is down", 'negative'),
                       ("The QA is down", 'negative'),
                       ("Slack Events are not coming", 'neutral'),
                       ("can we speed up the development a little", 'negative'),
                       ("We are already lagging behind", 'negative'),
                       ("There are too many bugs in the current build", 'negative'),
                       ("We don't want the build to be delayed again", 'negative'),
                       ("It is annoying to ask this every time", 'negative'),
                       ("There seems to be something wrong", 'negative'),
                       ("It is not my responsibility to always follow up", 'negative'),
                       ("The dev team needs to be more alert", 'negative'),
                       ("test coverage is very low", "negative"),
                       ("I'm dissapointed at the outcome", 'negative'),
                       ("I can only hope you complete this in time", 'negative'),
                       ("you need to get serious now", 'negative'),
                       ("We are exceeding the timelines", 'negative'),
                       ("We ought to make this right", 'negative'),
                       ("This will not complete in time", 'negative'),
                       ("This is not what we expected", 'negative'),
                       ("This is not what we are looking for", 'negative'),
                       ("you can do better", 'negative'),
                       ("This view is horrible", 'negative'),
                       ("I am sure you can find a better way", 'negative'),
                       ("I don't think this will work", 'negative'),
                       ("I don't feel this is the right way to go about this ticket", 'negative')]

test_data_slack = [
    (['feel', 'happy', 'this', 'morning'], 'positive'),
    (['that', 'should', 'be', 'okay'], 'neutral'),
    (['think', 'you', 'can', 'go', 'ahead', 'with', 'this', 'approach'], 'neutral'),
    (['larry', 'not', 'sure', 'if', 'this', 'is', 'the', 'right', 'way'], 'negative'),
    (['not', 'like', 'that', 'man'], 'negative'),
    (['product', 'not', 'great'], 'negative'),
    (['bugging', 'me', 'this', 'thing'], 'negative')]

